### ISSUE TITLE
Custom formatters: someModule not found

### ISSUE THREAD

**Issue by iamruslanbakirov** [messageformat/messageformat#247] opened 2019-07-24 09:56 UTC
I use this library in other module: ngx-translate-messageformat-compiler.
I create custom formatter 
`
 {
      provide: MESSAGE_FORMAT_CONFIG,
      useValue: {
        formatters: { myDuration: v => moment.duration(v, 'minutes').humanize() }
      }
}
`
and in runtime i receive exception 

> ERROR ReferenceError: moment__WEBPACK_IMPORTED_MODULE_25__ is not defined

I think is relation with eval custom formatter, maybe do you have resolve for this problem (without setup moment as global)?

**Comment by eemeli** [comment] 2019-07-24 11:32
This might be more appropriate to file as an issue in the ngx-translate-messageformat-compiler repo?

My guess would be that `moment` might not be available in your runtime.

**Comment by iamruslanbakirov** [comment] 2019-07-24 12:16
@eemeli The Moment available only scope where I declaration my function, when this function make to string, and evaluate in some other scope, variable Moment be not available

`
let func;

{
let a = 1;
function log(){console.log('var a is' ,a) }

func = log.toString()
}

eval(func);

log(); // Uncaught ReferenceError: a is not defined

`

**Comment by iamruslanbakirov** [comment] 2019-07-24 12:26
https://github.com/messageformat/messageformat/blob/cd47ed7db2b7a4f5e21df4cd6284ae3f7dad05a1/packages/messageformat/src/messageformat.js#L388

i mean, when you call new Function - you lost my scope

**Comment by eemeli** [comment] 2020-11-18 16:41
Closing, as this is effectively working as intended.

**Closed by eemeli** 2020-11-18 16:41 UTC
